### PR TITLE
remove font-face & background-image for less loading and better readability

### PR DESCRIPTION
**Pull request by jancborchardt**
Befre & after:
capture du 2016-12-27 13-17-06

What do you think @xMartin @jorinvo? :)

### CODE REVIEW

**Comment by xMartin** [comment]
I actually like the old font for what Litewrite advertises as I understand it: Nice interface for writing longer texts. But for smaller screens/windows the font-size should be decreased.

And performance-wise, are there concrete issues on typical device/connection scenarios?

Anyway, I do like the new font look, too, and simpler can be better.

**Comment by skddc** [comment]
I also like the current font a lot, and I think it's one of the nicest things about Litewrite. :)

And I also don't have any performance issues with it really. The font loading itself is basically instant once cached, because the font files are listed in https://litewrite.net/cache.manifest

**Comment by jancborchardt** [comment]
Yeah I mean @xMartin when you said it seems intended for writing but you want to use it for quick notes, I realized that it really has some aspects which hinder flexibility. The serif font definitely is one part.

Performance-wise the initial load on a slow mobile connection might be noticeable. The performance is not my primary concern, but mostly that the current look, while whimsical and nice, seems a bit dated, no? Especially if it limits what people think they can use or would like to use it for.

**Comment by jorinvo** [comment]
I like the argument for simplicity.
Apart from that, I don't have any preferences.
Maybe we can change the default font to get rid of the dependency, but still reference *Alegreya* so @skddc can install the font locally and keep using it :)

**Comment by skddc** [comment]
I disagree about simplicity. I think both fonts are equally simple. But while one is unique and lends Litewrite a lot of its charme imo, the other one looks boring and generic to me. With an app that has almost no interface, the font is definitely one of the most important considerations, so please actually consider all arguments, not just one. Thanks!

**Comment by jorinvo** [comment]
For me it's also fine to keep the current font.
Can close this PR. 
@skddc, @jancborchardt, you can decide on this.

**Comment by skddc** [comment]
Perhaps a simple checkbox setting somewhere would be easy enough to implement? Like this:

* [x] Use system fonts

**Comment by jancborchardt** [comment]
Ok, closing then. :)

**Comment by skddc** [comment]
Thanks anyway! And thanks for Litewrite. :)

Unmerged pull requests are so sad.

sad-rain

**Pull request closed without merging**
