### PR TITLE
Use Ctrl as hot key on Windows and Linux

### LINKED ISSUE #297: Alt+Tab in Windows triggers sidebar. Alt also triggers Firefox's menu bar
When I have a narrow window, such that litewrite hides its sidebar, and I alt+tab away from my browser window on Windows, litewrite opens its sidebar.
Alt also triggers Firefox's menu bar.

For those reasons, I think Alt should not be used as a keyboard shortcut by itself, at least on Windows.

### PR DESCRIPTION
**Pull request by brianpeiris**
Resolves #297

### CODE REVIEW

**Comment by jorinvo** [comment]
Thank you again @brianpeiris! It's really great when people help solving issues since lately I don't have time to work on Litewrite anymore :)

**Comment by raucao** [comment]
Actually, `ctrl-d` on Linux adds a new bookmark (add least in FF), and `ctrl-up/down` scrolls all the way to the top or bottom (modifying the arrow key that way). So I'm not sure these are the best to use.

**Comment by brianpeiris** [comment]
@skddc Ah, though I think that's a fair tradeoff to make for Litewrite. You can still use Home and End to scroll a page. You're right about the bookmark shortcut though, not sure how many Litewrite users bookmark individual Litewrite docs. 

Perhaps Ctrl+Shift would be a better combo?

**Comment by raucao** [comment]
I guess it's all subjective. Personally, I would use the ctrl-arrow scrolls before bookmarking, but then again I actually use the space key for scrolling quickly. Was just a general observation about disabling some system shortcuts, but I agree that the trade-offs could be OK in Litewrite's case.

**Comment by brianpeiris** [comment]
After having used it for a few weeks now, I regret making Ctrl the new hot key. I use Ctrl keys to move my text cursor around far more than I had realized. I'll try some other solutions and open a new issue with a proposal.

**Pull request merged**
