### PR TITLE
Appcache

### PR DESCRIPTION
**Pull request by jorinvo**
This addresses #231.
I really want everyone to be able to have use litewrite offline, not just on litewrite.net.
Since this is so simple, we should add it.

I also know that Appcache is deprecated. But it has way better browser support than service workers at the moment.
We can still switch later.

@jancborchardt do you think we should translate the reload [message](https://github.com/litewrite/litewrite/compare/gh-pages...litewrite:appcache?expand=1#diff-2b4ca49d4bb0a774c4d4c1672d7aa781R62)?

### CODE REVIEW

**Comment by jancborchardt** [comment]
Doesn’t 5apps already take care of this? Or do you mean independently from that? Maybe it then messes with deployment cc @skddc

**Comment by jorinvo** [comment]
@jancborchardt yes, in the moment we use 5apps for this. 
We can just disable this in the 5apps settings.
I really want the app to run everywhere, not just on litewrite.net.  That's why I would like to include this here.

**Comment by jancborchardt** [comment]
Okidoke, good call.

You wanna review @vovkkk @maxlath @JohnTroony @3demax? :)

**Comment by jorinvo** [comment]
So I added the `updateCache` message to the translations.
Would be cool to get Russian and French there too :wink:

**Comment by jorinvo** [comment]
I'm sorry. I messed up the commits :confused:. I open a new PR

**Comment by maxlath** [comment]
@jorinvo here is the French i18n #251, let me know if it isn't the right branch for the PR :)

**Pull request closed without merging**
