### PR TITLE
Change build setup to make working on litewrite possible again

### PR DESCRIPTION
**Pull request by jorinvo**
After a long break I would like to continue working on litewrite again (sorry for that).
However, with the old setup I wasn't even able to run the project on my local machine anymore.

Switching to webpack and commonjs makes this possible again.
Also, I manage all libs (if possible) with npm now.
While doing that I also updated the remotestorage version.

I would like to get this on gh-pages soon since the current version there is  pretty much unusable..
After some testing, would also be nice to get it to litewrite.net but we should test first if all the new functionality works (including the sharing feature).

Cheers!

Jorin

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice, cool you’re back again! :)

Since this is quite a complex change, we should test this thoroughly and get it in. Can you help testing @maxlath @vovkkk @skddc @galfert @JohnTroony

**Comment by jancborchardt** [comment]
@krrrcks @Vinnl @fkooman maybe you’d like to help testing as well? :)

**Comment by galfert** [comment]
Very cool indeed. I will give this a test spin.

**Comment by fkooman** [comment]
@jancborchardt you mean testing it locally? or is the new version hosted somewhere?

**Comment by jancborchardt** [comment]
@fkooman yep, locally for now, because this is only a pull request and hence not hosted anywhere. ;)

**Comment by jorinvo** [comment]
@jancborchardt, yes it's a lot going in terms of setup, but no changes to the actual application code.
It works better than the unusable gh-pages version already. So we could try it there instead...

@fkooman, here is a hosted version so you don't need to install it: https://jorin.lepus.uberspace.de/litewrite/

**Comment by Vinnl** [comment]
I haven't checked out building it yet, but the hosted version has an incorrect height for the editor for me: http://i.imgur.com/ZHujq6H.png (Notice how the bottom line is cut off.) I also can't scroll using the mouse wheel, only by moving the caret to lines below.

This issue is not present when I visit litewrite.net.

**Comment by fkooman** [comment]
@jorinvo thanks! it seems when sharing a document it is not updated if you then modify the document...

**Comment by jorinvo** [comment]
@fkooman yes. See #230. This PR is doesn't have a production ready version. 
It just fixes gh-pages current state.
I'll fix sharing in a separate PR.

**Comment by maxlath** [comment]
from @jorinvo's hosted version, everything seems fine out of the fact that a#share doesn't trigger anything: could it be normal as I didn't connect a remote storage?

**Comment by jancborchardt** [comment]
I get the same problem as @Vinnl with the erroneous margins. This doesn’t happen with litewrite.net

**Comment by jorinvo** [comment]
@maxlath see #230, we still need to work on the sharing feature.

@Vinnl, @jancborchardt thanks, this seems to be a problem with [autosize](https://github.com/jackmoore/autosize). We should look into that. I tried it at litewrite.net and there I see similar issues with not resizing properly.
We should definitely look into that. I created an issue for that #232. But not as part of this PR.

**Comment by galfert** [comment]
Good news is that I can do a build and also start a local server.

Bad news is that my changes don't seem to be pushed to the remote while connected. When I change a document or create a new one, I don't see any PUT requests in the network panel. And when I disconnect and reconnect again, my changes from before are gone.

**Comment by jorinvo** [comment]
Thank you @galfert for testing this!
I also tried it again and it seems like it's not even updating the local version. After refreshing everything is gone.
I was trying if it worked before switching remotestorage to 0.12 but it was already broken _before_ that.
In fact, it's even broken on litewrite.github.io/litewrite (if you get the app to load there) :smile:
However, it's still working on litewrite.net. Last time we deployed was 4b01ccbfcda9550172b1dfe6517cceb57df94b85. That's _before_ @galfert updated RS to 0.11 (0206c59358fc718267899de19700704c18a61d5f).
So, I would assume it's broken with this change.

I tried looking into it and the app code seems to handle the saving as usual. However the call to remoteStorage [here](https://github.com/litewrite/litewrite/blob/setup/lib/remotestorage-documents.js#L109) returns a Promise that is never resolved.
Oddly it there is also no error. But if I add a `.catch()` handler I get something. Surprisingly I don't get any error, instead I get the expected result in catch (`id'', doc{}`).
Any help with this is welcome!

**Comment by skddc** [comment]
> Might this be an issue with using privateClient.scope( ).extend( )?
> I don't see this being used in any other module..

It definitely doesn't seem like a good thing to do on first sight.

**Comment by jorinvo** [comment]
> It definitely doesn't seem like a good thing to do on first sight.
We implemented it this way at the unhosted unconference back then. 
They told me this is the new way to build modules.
But good to know, so I might change the remotestorage.documents module then.

**Comment by skddc** [comment]
Unfortunately modules are still the main construction site of rs.js, and there's not really a standard way to do things. So anything goes. :)

**Comment by jorinvo** [comment]
@skddc I'm starting to doubt if modules are even a good idea. Most modules have quiet application specific logic.
Maybe it would be better to just share the underlying datatypes and not the module code...

**Comment by skddc** [comment]
I think modules make sense, but that the data types should be seperated from the module definition in any case, so that they can be used outside of modules, and more importantly, in multiple modules at once. There's conceptual work to be done first for that to be possible though.

**Comment by jorinvo** [comment]
Thank you everyone for helping with testing here!

Nice that we found some more bugs!
I created separate issues for them since non of them are new with this PR.
We will fix them separately.

@jancborchardt I would merge this now and we continue fixing the issues with separate PRs.

**Comment by jancborchardt** [comment]
@jorinvo yup, cool! The only important thing is that before we deploy to litewrite.net it should of course work as well or even better than it already does. :)

**Comment by jorinvo** [comment]
@jancborchardt sure :wink: 

I labeled all issues I would like to fix before deploying with "priority".

**Comment by jancborchardt** [comment]
Yeah, great – the priority tag works fine. :)

**Pull request merged**
