### PR TITLE
fr i18n update

### PR DESCRIPTION
**Pull request by maxlath**
I translated "Load it?" by "Load it now?" as just "Load it" sounded weird/unclear

### CODE REVIEW

**Comment by jorinvo** [comment]
Awesome! Thanks for the fast response!
Do you we should also change "load it" in English maybe? 
"Reload now" maybe?

**Comment by maxlath** [comment]
"Load it now" maybe?
But "Load it" is already rather clear, it was just that "La charger" in French wasn't elegant

**Comment by jorinvo** [comment]
Alright, I leave it for now :wink:

**Comment by jancborchardt** [comment]
How about »Reload?« or »Refresh?« that’s already browser lingo and much shorter.

The first sentence could also be »New Litewrite version available.« or something. Shorter and more quick to read. :)

**Comment by jorinvo** [comment]
Sounds good! I update it.

**Pull request merged**
