### PR TITLE
corrections

### PR DESCRIPTION
**Pull request by maxlath**
* turning verbs to the infinitive form as it seem to be the case in the German version
* translating modified by "last modification" as in German

### CODE REVIEW

**Comment by jorinvo** [comment]
Thank you so much fo the quick help!

Did you also check the timeAgo functions there (secondAgo and so on)? 
Are they ok?

**Comment by maxlath** [comment]
yes, prefect! :)

**Comment by jorinvo** [comment]
Awesome! Thank you!

**Comment by maxlath** [comment]
you're welcome!

**Comment by jancborchardt** [comment]
Cool! Thanks @maxlath for contributing. :)

**Pull request merged**
