### PR TITLE
Appcache manifest

### PR DESCRIPTION
**Pull request by jorinvo**
>This addresses #231.
I really want everyone to be able to have use litewrite offline, not just on litewrite.net.
Since this is so simple, we should add it.

>I also know that Appcache is deprecated. But it has way better browser support than service workers at the moment.
We can still switch later.

### CODE REVIEW

**Comment by jorinvo** [comment]
@3demax would you mind helping out with the Russian translation once again?
That would be awesome!

As you can see with the French translation, it's just one phrase we need: https://github.com/litewrite/litewrite/commit/352f1eec3a54970816c963e4c56e3e69fe0e4de3.

**Comment by 3demax** [comment]
@jorinvo Sorry, was busy lately. [Here you go](https://github.com/litewrite/litewrite/pull/252)

**Comment by jorinvo** [comment]
@3demax thank you so much!
No need to be sorry. It's awesome that you take your time to help out!

**Comment by jorinvo** [comment]
It's looking good. Let's try this on [gh-pages](litewrite.github.io/litewrite)

**Pull request merged**
