### PR TITLE
Update remotestorage.js to 0.11.1

### PR DESCRIPTION
**Pull request by galfert**
I tried updating the remoteStorage version to 0.11.1. The new AMD build requires the Bluebird library now, so I included it as well.

When running the server with `grunt` and loading the app, I get an error `TypeError: ShareView is not a constructor` in `app.js` line 27.

Not sure what I am doing wrong, so any pointers are greatly appreciated.

### CODE REVIEW

**Comment by jorin-vogel** [comment]
Hey @galfert! Thank you so much for your effort to keep litewrite up to date!
Sadly I haven't found much time to do so lately..
I tried to reproduce your error but never get it. Can you check your setup again? Maybe clone your fork again and try it?

**Comment by jorin-vogel** [comment]
I just merge this version into the `gh-pages` branch so we can also test it at http://litewrite.github.io/litewrite.

**Comment by jorin-vogel** [comment]
I observe some similar errors to yours appearing from time to time. 
Some objects or functions can't be found.
Maybe it's related to requirejs. It's worth thinking about switching to something else anyways..

**Comment by skddc** [comment]
It's really important to upgrade to a stable rs.js version in any case. I get hardcore sync errors that were fixed a year ago right now. Making the app basically useless for me atm.

**Pull request merged**
