### PR TITLE
Complete sharing feature

### PR DESCRIPTION
**Pull request by jorinvo**
I implemented the unshare feature.
It's working, but we need some styling.
Also, we need translations for "unshare". I can't even come up with a good German word :D

I also played with the style of the published document a bit.

@jancborchardt if you have some time some day and could help with the styles would be awesome :wink:

### CODE REVIEW

**Comment by jorinvo** [comment]
Added some really, really basic styling.
@jancborchardt any succestions for improvements?

full
hover
mobile
shared

**Comment by jorinvo** [comment]
Also, we still need to translate "unshare". 
3demax and @maxlath, if you could help once more, would be awesome!

I'm not really happy with the labels "open" and "unshare" though...
If you have better ideas please feel free to change it!

**Comment by jorinvo** [comment]
Sorry @3demax forgot the "@" in the mention.
Is "скрывать" a good translation for unshare?

**Comment by 3demax** [comment]
@jorinvo Nope. This one is tough, and can't be expressed with one word in russian :)
see https://github.com/litewrite/litewrite/pull/256
also with couple more fixes

**Comment by jorinvo** [comment]
@jancborchardt if you don't have any comments at the moment, I would put this on gh-pages now.
We can still improve the design later on.

**Pull request merged**
