### PR TITLE
Forgot weeks when switching to custom timeAgo

### PR DESCRIPTION
**Pull request by jorinvo**
Still need Russian translation.

### CODE REVIEW

**Comment by jancborchardt** [comment]
@3demax can you review this?

**Comment by jorinvo** [comment]
Would be awesome if you could help out one more time :wink:

**Comment by 3demax** [comment]
No problem, guys.
https://github.com/litewrite/litewrite/pull/240

**Comment by jorinvo** [comment]
Thank you so much for you help @3demax!

**Pull request merged**
