### PR TITLE
Cordova packaging

### PR DESCRIPTION
**Pull request by khertan**
#### To run on android :
    cd cordova
    cordova platform add android
    cordova plugin restore
    cordova run android

Require https://github.com/cozy/cozy-proxy/pull/216 to works with remotestorage.js in cozycloud

### CODE REVIEW

**Comment by jorinvo** [comment]
Awesome that you got it work!
As you can see this are quiet a lot of files to add to the repository.
Instead of adding all this directly, I would prefer to just provide a script for people to build the cordova version.
Also, instead of requiring the user to install cordova globally, the script could install it locally.

Later on we could also provide pre-build Android `apk` files via the Github releases.

**Comment by khertan** [comment]
Indeed that s a lot of file, is there any problem keeping the cordova dir ? i ll also clean plugin folder and others not need, add a script to install needed things. i ll try to add also Android Intent

**Comment by jorinvo** [comment]
@khertan would be nicer if we don't need the directory but can create it on the fly...
But I don't really know how to make the dev workflow pleasant for the cordova app.
I try to get it running on my phone on the weekend :)

**Comment by skddc** [comment]
You'll have some config files in the Cordova dir that you won't want to keep out of the repo. Also, when working with others, it's generally a good idea to have the whole Cordova setup checked in. At least that's how it works best for us at 5apps with the Cordova apps we're building.

**Comment by jorinvo** [comment]
Thanks @skddc. Last time I built a Cordova app is over a year ago. But I guess we would have to symlink the litewrite files into the _www/_ cordova folder?

I'm just concerned that the project could be too focused to the cordova build with this.
I don't want anyone who just wants to put litewrite on their webserver to deal with all those cordova files.
Maybe it would make more sense to have the cordova version of litewrite in a separate repo. We could publish litewrite via npm or something and include it over there.

I also think about other build targets in the future (electron, owncloud, ...) and we should keep them separated.

**Comment by skddc** [comment]
> Maybe it would make more sense to have the cordova version of litewrite in a separate repo. We could publish litewrite via npm or something and include it over there.

> i could also maintain a git repository which contain only the packaging

:+1:

**Comment by khertan** [comment]
I ll let open for the moment

"I'm just concerned that the project become too focused on the cordova build with this."
I agree

I think of an electron build later too. I m actually trying to integrate Android Intent and share via Android Intent. So, yes i think it s better to keep such modifications in an other repository.

I keep open until i setup a better organized repo

**Comment by khertan** [comment]
As it s better to do some modification for use on mobile, i ll keep a fork synced and close the pull request.

Regards

**Comment by jorinvo** [comment]
@khertan thanks! What kind of modifications do you have in mind?
Would be nice if we could adjust the core to make  it reusable.

**Comment by khertan** [comment]
Hi,

"thanks! What kind of modifications do you have in mind ?"

* modification of sharing feature to use Android Intent (from litewrite to
other android app) (not really useable without cordova and the right plugin)
* modification if used in cordova to lower font size (i should make
something reusable)
* modification for sharing intent feature (from an other app to
litewrite)(not really useable without cordova and the right plugin)

I ve also tryed to not include all things in repository, like platform
folder, but it s require manual modification in AndroidManifest.xml :(

Regards,

**Comment by jorinvo** [comment]
Thanks for sharing!
This helps a lot for planning how to make litewrite more modular in the future. 

- The first one is basically like remotestorage sharing - so we should have a hook for sharing anyways.
- I don't really understand the part with the font size. Shouldn't the mobile design be the same as in the browser? Or you also think we should lower the font size in the mobile browser version?
- I would be interested how you implemented this. (I didn't check the code yet). Maybe we find more usecases for this with other platforms.

But for now keeping a separate fork is probably the easiest solution...

**Pull request closed without merging**
