### PR TITLE
No moment

### PR DESCRIPTION
**Pull request by jorinvo**
This removes moment.js. 
The only thing we use is the "time ago" feature.
I implemented a simple version of this.
We just need the right translations for our languages:

English and German should be fine.

I tried French too, but there might be some errors:
https://github.com/litewrite/litewrite/blob/no-moment/src/translations/fr.js
@maxlath I saw you helped with the last translation. Would you mind having a look if this is already?

Could need some help with Russian.
https://github.com/litewrite/litewrite/blob/no-moment/src/translations/ru.js
@3demax I saw you helped with the last translation. If you could help out here, would be really helpful.
I don't know if Russian has more complicated structures. If so, we can change the logic for sure.
I tried using the [moment.js](https://github.com/moment/moment/blob/develop/locale/ru.js) code but couldn't figure it out.

Thank you so much!

Cheers

Jorin

### CODE REVIEW

**Comment by maxlath** [comment]
[done!](https://github.com/litewrite/litewrite/pull/229)

**Comment by jancborchardt** [comment]
Yeah, good call on removing libraries we don’t really need. :)

**Comment by 3demax** [comment]
@jorinvo: Unfortunately, Russian does have three plural forms depending on the number. You can see how funny it is by taking a look at plural function :)
I took this snippet from moment.js and adapted slightly:
```
function plural(word, num) {
        var forms = word.split('_');
        return num % 10 === 1 && num % 100 !== 11 ? forms[0] : (num % 10 >= 2 && num % 10 <= 4 && (num % 100 < 10 || num % 100 >= 20) ? forms[1] : forms[2]);
    }
    function relativeTimeWithPlural(number, key) {
        var format = {
            'mm': 'минуту_минуты_минут',
            'hh': 'час_часа_часов',
            'dd': 'день_дня_дней',
            'MM': 'месяц_месяца_месяцев',
            'yy': 'год_года_лет'
        };
        if (key === 'm') {
            return withoutSuffix ? 'минута' : 'минуту';
        }
        else {
            return number + ' ' + plural(format[key], +number);
        }
    }
```

This is adapted specificly for frases like "{verb in past simple} {time} ago", and in your case would only work with "modified"

So if you want to get proper string call it like ```relativeTimeWithPlural(19, 'dd') + " назад"```

E.g.
```
relativeTimeWithPlural(19, 'dd') + " назад"
"19 дней назад"
relativeTimeWithPlural(3, 'yy') + " назад"
"3 года назад"
```

**Comment by 3demax** [comment]
I guess it's better to have a function timeAgo for all languages.
Created a [pull request #233](https://github.com/litewrite/litewrite/pull/233)
Please take a look.

**Comment by jorinvo** [comment]
I changed it a little bit so each language still has function for the different quantifiers but has to do the pluralizing itself.
This should also work for the slavic languages now.
Unfortuanately the moment.js code doesn't have seconds specified.
@3demax would you be so kind and have another look at this?
That would be super helpful!

I hope the other parts work now too.

**Comment by 3demax** [comment]
@jorinvo: I overcame my laziness and [refactored utils a bit](https://github.com/litewrite/litewrite/pull/235)

**Comment by jorinvo** [comment]
@3demax oh no! Seems like we did (almost) the same work now at the same time!
I'm so sorry :frowning:

**Comment by jorinvo** [comment]
@3demax still, thank you so much for doing! 
The translations from your version are definitely helpful!

**Comment by 3demax** [comment]
No problem! I just have thought about different edge cases, like:
"edited a day ago", but "modified 3 days ago"
"изменён секунду назад", but "изменён 2 секунды назад" 
I have tested it and it works well, so it could be merged

**Comment by 3demax** [comment]
@jorinvo What do you think?

**Comment by jorinvo** [comment]
@3demax I don't really see what you mean. Did you have a look at my update over here: https://github.com/litewrite/litewrite/commit/dbe1c185da5c7d68c64db4e6503203fae30f6cf4
Isn't this handling the same edge cases? Am I forgetting something there?

**Comment by 3demax** [comment]
@jorinvo: yes, you've missed "назад" ("ago") part. Otherwise, it seems to be fine.
I really appreciate your work, (and I hate to tell this) but it does have more of boilerplate code :\

**Comment by jorinvo** [comment]
@3demax thanks, and thank you for your help!

You are right about the boilerplate. I put two versions [here](https://gist.github.com/jorinvo/b4eaa64bca5348aa2709) for comparison.
Looking at them, I would argue that the difference is pretty small and I would be fine with either version.
I wrote it the style I did because I prefer dumb code. I don't want to have to think when looking at the code. I just want to know what it does.

But as I said, in this case the difference is really not that big.
I leave it like this for now. 

And thank you again! I really appreciate your help!

**Pull request merged**
